repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.4
    hooks:
      - id: terraform_fmt
      - id: terraform_validate

  - repo: local
    hooks:
      - id: rm-tf-lock
        name: Terraform clean
        entry: bash
        language: system
        pass_filenames: false
        args:
          - -c
          - |
            #!/bin/bash
            set -euo pipefail
            IFS=$'\n\t'
            find . -type d -name '.terraform' -exec rm -rf {} +
            find . -type f -name '.terraform.lock.hcl' -exec rm {} +

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.18.0
    hooks:
      - id: terraform-docs-go
        args:
          [
            "markdown",
            "table",
            "--output-file",
            "README.md",
            "--recursive",
            "--recursive-path=./modules",
            ".",
          ]
